### ISSUE TITLE
Support for resolving parameters in effects for numeric formulas

### ISSUE THREAD

**Issue by schwab** [garydoranjr/pyddl#2]
While trying to use pyddl to solve an optimization problem for a business plan simulator I ran into the limitation that actions cannot utilize parameters on numeric effects as they can in the precondition section.  For instance this Action is able to use parameters for preconditions... 
```
 Action("buy_item",
            parameters=(("product_id","id"),),
            preconditions=((">",("cash", "on_hand"),("cost","id")),),
```
Which has the expected effect of only preforming the action when the cash on_hand is > then the  cost of the product.  IOW, the precondition is capable of looking up the cost of whatever product is passed into the action.  This assumes of course that we have problem parameters like 
```
problem = Problem(domain, {
    "product_id":("3356","5594","3405"),
```
and an init like : 
```
 init=(
        ("=",("cash","on_hand"),1000),
        ("=",("cost","3356"), 111),
        ("=",("cost","5594"), 126),
        ("=",("cost","3405"), 238),
...
```
 However, if I attempt to lookup the cost in the effects section using a mathematical effect like : 
```
effects=(
                ("+=",("cash", "on_hand"),("cost","id")),
```
We get an error that the key cannot be found. 

Is there anyway to force the code to do a lookup on the  += algorithm for the cost id tuple like it did for us in the preconditions?  This would allow for much more dynamic actions to be created.

**Comment by garydoranjr** [comment]
Hi @schwab, thank you for this recommendation. I made an attempt to implement support for this functionality. Would you see if it works for you? I created a new branch with the change and a new `numeric_effects.py` script that has a simple problem along the lines of what you described to exercise the new functionality. I'll create a pull request, and if it works the way you expect it to, then I'll merge it into the master branch.

**Comment by garydoranjr** [comment]
@schwab thanks! I've merged the new functionality into master.
